#!/usr/bin/env bash

# simple screenlocker using i3lock that creates ablurred screenshot to overlay

PICTURE=/tmp/i3lock.png
OUT=/tmp/i3lock-blurred.png
SCALE=2
# BLUR="5x4"

scrot -z $PICTURE

# magick $PICTURE -scale 20% -blur $BLUR -scale 500% $PICTURE

ffmpeg -y -loglevel quiet \
	-i $PICTURE \
	-vf "scale=iw/$SCALE:ih/$SCALE:flags=fast_bilinear,gblur=sigma=4,scale=iw*$SCALE:ih*$SCALE:flags=neighbor" \
	$OUT

i3lock -i $OUT &
sleep 5
xset +dpms
xset dpms force off

wait

xset s off -dpms
shred $PICTURE $OUT
rm $PICTURE $OUT
