unbind C-b
set -g prefix C-a
set-window-option -g xterm-keys on
set -g history-limit 100000

#set inactive/active window styles
# set -g window-style 'fg=colour247,bg=colour236'
# set -g window-active-style 'fg=colour250,bg=black'
# set -g default-terminal "screen-256color"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind H resize-pane -L 10
bind J resize-pane -D 10
bind K resize-pane -U 10
bind L resize-pane -R 10

bind % split-window -h -c "#{pane_current_path}"
bind '"' split-window -c "#{pane_current_path}"

bind -T copy-mode-vi Enter send-keys -X copy-pipe-and-cancel 'xclip -selection clipboard'

set -g allow-rename off
set -g escape-time 0 # zero delay on sending esc key to terminal (vim lag)
setw -g mode-keys vi
setw -g aggressive-resize on # use size of the active window, not the smallest one
setw -g monitor-activity on # highlight activity in other window
set -g visual-activity off
set -g renumber-windows on # renumber active windows on close

set-window-option -g window-status-separator ""
set-window-option -g window-status-current-format " *#{b:pane_current_path} "
set-window-option -g window-status-format " #{b:pane_current_path} "
